name: Sync

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/Auxilor/EcoEnchants.git || true
          git fetch upstream

      - name: Pull and merge upstream changes
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories

      - name: Push changes to current repository
        run: |
          git push origin master
